# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181125_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_brief',
            new_name='goods_brief',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_desc',
            new_name='goods_desc',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='good_sn',
            new_name='goods_sn',
        ),
    ]
