# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181125_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='good_front_image',
            new_name='goods_front_image',
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brands/'),
        ),
    ]
