# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 16:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20181213_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
