# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20181214_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='是否热销', verbose_name='是否热销'),
        ),
    ]
