# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20181216_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='轮播图'),
        ),
    ]
