# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20181220_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='brands/'),
        ),
    ]
