# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_remove_orderinfo_nonce_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='订单信息'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('WAIT_BUYER_PAY', '交易创建，等待买家付款'), ('TRADE_CLOSED', '未付款交易超时关闭，或支付完成后全额退款'), ('TRADE_SUCCESS', '交易支付成功'), ('TRADE_FINISHED', '交易结束，不可退款'), ('paying', '待支付')], default='paying', max_length=20, verbose_name='订单状态'),
        ),
    ]
