# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0009_auto_20181214_1615'),
        ('user_operation', '0003_auto_20181125_1332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
