# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0006_auto_20181216_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='', max_length=100, validators=['城', '市']),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=100, validators=['省', '份']),
        ),
    ]
